If you wish to use Redis to cache results then you need to have the Lettuce configuration dependency on your classpath.
Lettuce is a non-blocking, reactive Redis client implementation and Micronaut provides an implementation that allows cached results to be read reactively.

Within your application configuration configure the Redis URL and Redis caches:

//TODO: Move YAML snippet to test
.Cache Configuration Example
[configuration]
----
redis:
    uri: redis://localhost
    caches:
        my-cache:
            expire-after-write: 1h
----

.Cache Configuration Example with a Dynamic Expiration policy
[configuration]
----
redis:
    uri: redis://localhost
    caches:
        my-cache:
            expiration-after-write-policy: <class path of class implementing ExpirationAfterWritePolicy>
----

- Expiration is based on result from an implementation of api:configuration.lettuce.cache.expiration.ExpirationAfterWritePolicy[]

include::{includedir}configurationProperties/io.micronaut.configuration.lettuce.cache.RedisCacheConfiguration.adoc[]

== Dynamic Caching

To get more flexibilty to about Caches, you can enable dynamic caching. Therefore no specific cache configuration is needed and the caches will be created dynamically at runtime.
The DefaultRedisCacheConfiguration will be used to setup the cache. "Static"- and "Dynamic"-caches can be used in parallel.

.DynamicCache Configuration Example
[configuration]
----
redis:
    uri: redis://localhost
    cache:
        dynamic:
            enabled: true
        expire-after-write: 1h
        expiration-after-write-policy: <class path of class implementing ExpirationAfterWritePolicy>
----
